### ISSUE TITLE
Reserch for Annotation in Frontend

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#704]
### Issue Description

We will research how we can implement W3 Annotations in our front-end. Then, we will start its implementation to prepare our frontend codebase for annotations.

### Tasks

Parts of the task:
- [x] Make research about annotations.
- [x] Start its implementation

### Deadline of the Issue

19.12.2023 - Tuesday - 12.00

### Reviewer

@yunusemrealtug 

### Deadline for the Review

19.12.2023 - Tuesday - 15.00

**Comment by elifkizilky** [comment]
- First, we should decide on what pages we should have annotation. 
  - In my opinion, since the main component of our platform is Games, we should have annotations on our _Game_ page. We can annotate the information parts of our game page and also the image of the game. This page has lots of small components in it, thus it may require a remarkable effort.
  - If time permits, we should have annotations on the thread page. I think this is easier since we have only text and image parts in the thread component. 
  - We can discuss if we should also have annotation in the comments if time permits.
  - Other pages are somewhat extensions of those components such as Games, Forums, Groups (which are composed of threads), etc. Thus it may be a satisfying outcome to have annotations on the game and thread page.


I found an example codebase in the front end from the previous year's project. I remember that customer also show that example to our group: here is the [link](https://github.com/bounswe/bounswe2022group2/blob/master/learnify/web/src/components/Post.js).

- For javascript, there is a text annotation library: [Recogito](https://github.com/recogito/recogito-js)
- For javascript, there is a image annotation library:  [Annotorious](https://annotorious.github.io/)

**Comment by elifkizilky** [comment]
I prepared a research page for annotation implementation for frontend: [research](https://github.com/bounswe/bounswe2023group7/wiki/Annotation-%E2%80%90-Frontend). There are example codes in this, also some explanation about the mechanism of annotations. I believe this may be useful while we implement it.

**Comment by elifkizilky** [comment]
I'm closing this issue, everyone learned annotations very well.
